### ISSUE TITLE
Create items with predefined options

### ISSUE THREAD

**Issue by ergrassa** [zerog-latte/rim#1]
Instead of:
```
- _id: Secure metal bar
  cat: valuables
  desc: Has holographic embossment
  opts:
    - weight
    - mint
    - amount
    - currency
```
should be
```
- _id: Secure 5oz gold bar
  cat: valuables
  desc: Has holographic embossment
  opts:
    - weight: 0.156
    - mint
    - amount: 5
    - currency: gold
```
